name: EnhancedTraps
version: '1.0'
main: org.mrdarkimc.enhancedtraps.EnhancedTraps
author: MrDarkiMC
website: https://t.me/doomgxard
api-version: '1.20'
softdepend:
  - FastAsyncWorldEdit
  - WorldEdit
  - WorldGuard
commands:
  enhancedtraps:
    aliases:
      - et
    usage: /et help
